import { Product } from "./types";

export const SHOP_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Classic Silk Wrap Evening Dress",
    brand: "Alshakir Couture",
    category: "Dresses",
    price: 95.5,
    originalPrice: 135.0,
    discount: "-29%",
    rating: 5,
    reviewsCount: 142,
    stockStatus: "Almost Sold Out",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "Crimson", hex: "#9E1C1C" },
      { name: "Emerald", hex: "#1B4D3E" },
    ],
    sizes: ["S", "M", "L"],
    tags: ["Evening", "Luxury", "Summer 2026"],
    isSale: true,
    isHot: true,
    description: "Crafted from lustrous silk-blend crepe, this floor-sweeping wrap silhouette features a flattering V-neckline, self-tie sash, and delicate fluid draping for sophisticated evening events.",
  },
  {
    id: 2,
    name: "Tailored Double-Breasted Trench Coat",
    brand: "FASCO Signature",
    category: "Outerwear",
    price: 180.0,
    originalPrice: 220.0,
    discount: "-18%",
    rating: 5,
    reviewsCount: 98,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Beige", hex: "#D4C3A3" },
      { name: "Charcoal", hex: "#333333" },
      { name: "Olive", hex: "#5C6B50" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tags: ["Outerwear", "Vintage Fits", "Formal"],
    isNew: true,
    isSale: true,
    description: "An iconic modern staple tailored from water-repellent structured cotton gabardine. Features signature horn-effect buttons, storm flaps, and a belted waist.",
  },
  {
    id: 3,
    name: "Relaxed Fit Cotton Blend Zipper Jacket",
    brand: "Fashion Hub",
    category: "Men",
    price: 110.0,
    originalPrice: 140.0,
    discount: "-21%",
    rating: 5,
    reviewsCount: 84,
    stockStatus: "Almost Sold Out",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Black", hex: "#111111" },
      { name: "Camel", hex: "#B8860B" },
      { name: "Navy", hex: "#1E2A38" },
    ],
    sizes: ["M", "L", "XL", "XXL"],
    tags: ["Streetwear", "Casual", "Men's Collection"],
    isHot: true,
    description: "Modern street jacket engineered with lightweight insulated cotton twill, brushed silver hardware, dual side-entry pockets, and clean ribbed trims.",
  },
  {
    id: 4,
    name: "Oversized Vintage Washed Denim Jacket",
    brand: "Urban Chic",
    category: "Denim",
    price: 120.0,
    originalPrice: 150.0,
    discount: "-20%",
    rating: 4,
    reviewsCount: 67,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Blue Wash", hex: "#4682B4" },
      { name: "Faded Black", hex: "#2B2B2B" },
      { name: "Off White", hex: "#F5F5DC" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["Denim", "Casual", "Vintage Fits"],
    isSale: true,
    description: "Premium heavy-weight 100% organic cotton denim with custom vintage hand-abrasion wash, dropped shoulders, and brass shank buttons.",
  },
  {
    id: 5,
    name: "Pure Linen Casual Button-Down Shirt",
    brand: "Monochrome Studio",
    category: "Men",
    price: 65.0,
    originalPrice: 85.0,
    discount: "-24%",
    rating: 5,
    reviewsCount: 112,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Sky Blue", hex: "#87CEEB" },
      { name: "Sand", hex: "#E6D7B8" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tags: ["Summer 2026", "Casual", "Essentials"],
    description: "Breathable, pre-washed pure European flax linen tailored with a camp collar, curved hem, and mother-of-pearl buttons for effortless resort styling.",
  },
  {
    id: 6,
    name: "Minimalist Italian Leather Shoulder Tote",
    brand: "Vogue Atelier",
    category: "Accessories",
    price: 145.0,
    originalPrice: 195.0,
    discount: "-26%",
    rating: 5,
    reviewsCount: 53,
    stockStatus: "Only 2 Left",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Cognac Brown", hex: "#8B4513" },
      { name: "Noir Black", hex: "#1C1C1C" },
      { name: "Cream", hex: "#FFFDD0" },
    ],
    sizes: ["M"],
    tags: ["Luxury", "Accessories", "Essentials"],
    isHot: true,
    isSale: true,
    description: "Full-grain calfskin leather bag with magnetic snap closure, reinforced top handles, an internal zipped divider, and embossed gold foil emblem.",
  },
  {
    id: 7,
    name: "Pleated Chiffon Midi Floral Dress",
    brand: "Zara",
    category: "Dresses",
    price: 88.0,
    originalPrice: 110.0,
    discount: "-20%",
    rating: 4,
    reviewsCount: 46,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Floral Pink", hex: "#E8A598" },
      { name: "Sage Green", hex: "#9CAF88" },
    ],
    sizes: ["XS", "S", "M", "L"],
    tags: ["Summer 2026", "Dresses", "Floral"],
    isNew: true,
    description: "Airy micro-pleated floral chiffon midi dress with tiered ruffle skirt, smocked bodice, and sheer balloon sleeves.",
  },
  {
    id: 8,
    name: "Fine Knit Cashmere Turtleneck Sweater",
    brand: "Prada",
    category: "Women",
    price: 135.0,
    originalPrice: 175.0,
    discount: "-23%",
    rating: 5,
    reviewsCount: 78,
    stockStatus: "Almost Sold Out",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Oatmeal", hex: "#E3DAC9" },
      { name: "Midnight Black", hex: "#0F0F0F" },
      { name: "Burgundy", hex: "#6B1D2F" },
    ],
    sizes: ["XS", "S", "M", "L"],
    tags: ["Luxury", "Winter", "Essentials"],
    description: "Ultra-soft Mongolian cashmere knit with ribbed neck, cuffs, and hem. Feather-light warmth and sophisticated clean draping.",
  },
  {
    id: 9,
    name: "High-Waisted Straight-Leg Vintage Trouser",
    brand: "Minis",
    category: "Women",
    price: 79.0,
    originalPrice: 99.0,
    discount: "-20%",
    rating: 5,
    reviewsCount: 92,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Taupe", hex: "#B38B6D" },
      { name: "Black", hex: "#000000" },
      { name: "Ivory", hex: "#FFFFF0" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["Formal", "Casual", "Vintage Fits"],
    isNew: true,
    description: "Impeccably tailored from a structured wool-viscose blend with front pleats, slant pockets, and pressed creased legs.",
  },
  {
    id: 10,
    name: "Structured Minimalist Leather Crossbody",
    brand: "Chanel",
    category: "Accessories",
    price: 165.0,
    originalPrice: 210.0,
    discount: "-21%",
    rating: 5,
    reviewsCount: 120,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Forest Green", hex: "#1E4D2B" },
      { name: "Black", hex: "#111111" },
      { name: "Caramel", hex: "#AF6E4D" },
    ],
    sizes: ["S"],
    tags: ["Luxury", "Accessories", "Streetwear"],
    isHot: true,
    description: "Compact boxy silhouette crafted from polished box calf leather with custom gold-toned turn-lock closure and adjustable strap.",
  },
  {
    id: 11,
    name: "Raw Selvedge Slim Tapered Jeans",
    brand: "Calvin Klein",
    category: "Denim",
    price: 115.0,
    originalPrice: 145.0,
    discount: "-20%",
    rating: 4,
    reviewsCount: 61,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Indigo", hex: "#2B3D52" },
      { name: "Washed Grey", hex: "#555555" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Denim", "Men's Collection", "Casual"],
    description: "13.5oz Japanese shuttle-loom selvedge denim woven with a touch of stretch for day-to-night flexibility and natural fading over time.",
  },
  {
    id: 12,
    name: "Classic Minimalist Leather Low-Top Sneaker",
    brand: "FASCO Signature",
    category: "Footwear",
    price: 125.0,
    originalPrice: 160.0,
    discount: "-22%",
    rating: 5,
    reviewsCount: 89,
    stockStatus: "Almost Sold Out",
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Triple White", hex: "#F9F9F9" },
      { name: "White/Navy", hex: "#1F2937" },
      { name: "All Black", hex: "#181818" },
    ],
    sizes: ["M", "L", "XL"],
    tags: ["Footwear", "Essentials", "Streetwear"],
    isNew: true,
    isSale: true,
    description: "Handcrafted in Portugal with buttery smooth Nappa leather, cushioned memory foam insoles, and durable stitched Margom rubber cup soles.",
  },
  {
    id: 13,
    name: "Satin Slip Midi Dress in Champagne",
    brand: "H&M",
    category: "Dresses",
    price: 72.0,
    originalPrice: 95.0,
    discount: "-24%",
    rating: 5,
    reviewsCount: 39,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Champagne", hex: "#F7E7CE" },
      { name: "Emerald", hex: "#046307" },
      { name: "Midnight", hex: "#121829" },
    ],
    sizes: ["XS", "S", "M", "L"],
    tags: ["Dresses", "Summer 2026", "Luxury"],
    isSale: true,
    description: "Bias-cut silky satin fabric that skims the body with adjustable cross-back spaghetti straps and a subtle side slit.",
  },
  {
    id: 14,
    name: "Heavyweight Boxy Fit Graphic Cotton Hoodie",
    brand: "Gucci",
    category: "Men",
    price: 155.0,
    originalPrice: 195.0,
    discount: "-20%",
    rating: 5,
    reviewsCount: 114,
    stockStatus: "Only 2 Left",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Heather Grey", hex: "#9E9E9E" },
      { name: "Jet Black", hex: "#0D0D0D" },
      { name: "Olive Green", hex: "#4A5D4E" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Streetwear", "Men's Collection", "Casual"],
    isHot: true,
    description: "480 GSM French Terry cotton hoodie with seamless double-layered hood, dropped shoulders, and subtle tonal embroidery.",
  },
  {
    id: 15,
    name: "Chunky Heeled Chelsea Ankle Boots",
    brand: "Prada",
    category: "Footwear",
    price: 195.0,
    originalPrice: 250.0,
    discount: "-22%",
    rating: 5,
    reviewsCount: 58,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Glossy Black", hex: "#000000" },
      { name: "Burgundy", hex: "#541212" },
    ],
    sizes: ["S", "M", "L"],
    tags: ["Footwear", "Luxury", "Vintage Fits"],
    isNew: true,
    description: "Polished spazzolato leather with stretchy elastic side gussets, pull tabs, and exaggerated lugged commando rubber soles.",
  },
  {
    id: 16,
    name: "Polarized Retro Gold Aviator Sunglasses",
    brand: "FASCO Signature",
    category: "Accessories",
    price: 55.0,
    originalPrice: 75.0,
    discount: "-27%",
    rating: 4,
    reviewsCount: 72,
    stockStatus: "In Stock",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80",
    colors: [
      { name: "Gold / Green", hex: "#D4AF37" },
      { name: "Silver / Smoke", hex: "#C0C0C0" },
      { name: "Matte Black", hex: "#222222" },
    ],
    sizes: ["M"],
    tags: ["Accessories", "Summer 2026", "Essentials"],
    isSale: true,
    description: "Stainless steel wire frames featuring 100% UV400 polarized crystal lenses with anti-reflective internal coating.",
  },
];

export const CATEGORIES_WITH_COUNTS = [
  { name: "All Products", count: 16 },
  { name: "Women", count: 4 },
  { name: "Men", count: 4 },
  { name: "Dresses", count: 3 },
  { name: "Outerwear", count: 2 },
  { name: "Denim", count: 2 },
  { name: "Accessories", count: 3 },
  { name: "Footwear", count: 2 },
];

export const BRANDS_LIST = [
  "FASCO Signature",
  "Alshakir Couture",
  "Urban Chic",
  "Monochrome Studio",
  "Vogue Atelier",
  "Zara",
  "H&M",
  "Gucci",
  "Prada",
  "Calvin Klein",
  "Chanel",
  "Minis",
];

export const COLOR_SWATCHES = [
  { name: "Black", hex: "#1A1A1A" },
  { name: "White", hex: "#FFFFFF", border: true },
  { name: "Beige", hex: "#D4C3A3" },
  { name: "Blue", hex: "#4682B4" },
  { name: "Crimson", hex: "#9E1C1C" },
  { name: "Olive", hex: "#5C6B50" },
  { name: "Forest Green", hex: "#1E4D2B" },
  { name: "Brown", hex: "#8B4513" },
  { name: "Pink", hex: "#E8A598" },
  { name: "Grey", hex: "#9E9E9E" },
];

export const SIZES_LIST = ["XS", "S", "M", "L", "XL", "XXL"] as const;

export const TAGS_LIST = [
  "Summer 2026",
  "Vintage Fits",
  "Luxury",
  "Casual",
  "Formal",
  "Streetwear",
  "Essentials",
  "Denim",
];
